// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Asset } from "./Asset";

export class AssetInfo {
  static encode(message: AssetInfo, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.owner);

    writer.uint32(16);
    writer.uint64(message.supplyNo);

    const assets = message.assets;
    for (let i: i32 = 0; i < assets.length; ++i) {
      writer.uint32(26);
      writer.fork();
      Asset.encode(assets[i], writer);
      writer.ldelim();
    }

    writer.uint32(32);
    writer.int64(message.startTime);

    writer.uint32(42);
    writer.string(message.mintAccount);

    writer.uint32(50);
    writer.string(message.tokenAccount);
  }

  static decode(reader: Reader, length: i32): AssetInfo {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AssetInfo();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.owner = reader.string();
          break;

        case 2:
          message.supplyNo = reader.uint64();
          break;

        case 3:
          message.assets.push(Asset.decode(reader, reader.uint32()));
          break;

        case 4:
          message.startTime = reader.int64();
          break;

        case 5:
          message.mintAccount = reader.string();
          break;

        case 6:
          message.tokenAccount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  owner: string;
  supplyNo: u64;
  assets: Array<Asset>;
  startTime: i64;
  mintAccount: string;
  tokenAccount: string;

  constructor(
    owner: string = "",
    supplyNo: u64 = 0,
    assets: Array<Asset> = [],
    startTime: i64 = 0,
    mintAccount: string = "",
    tokenAccount: string = ""
  ) {
    this.owner = owner;
    this.supplyNo = supplyNo;
    this.assets = assets;
    this.startTime = startTime;
    this.mintAccount = mintAccount;
    this.tokenAccount = tokenAccount;
  }
}
