// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { BurnEvent } from "./BurnEvent";
import { MintEvent } from "./MintEvent";
import { StakeEvent } from "./StakeEvent";
import { UnstakeEvent } from "./UnstakeEvent";
import { WrapEvent } from "./WrapEvent";
import { InitAssetManager } from "./InitAssetManager";
import { Stake } from "./Stake";
import { Unstake } from "./Unstake";
import { WrapAsset } from "./WrapAsset";
import { UnwrapAsset } from "./UnwrapAsset";

export class Data {
  static encode(message: Data, writer: Writer): void {
    const burnEventList = message.burnEventList;
    for (let i: i32 = 0; i < burnEventList.length; ++i) {
      writer.uint32(10);
      writer.fork();
      BurnEvent.encode(burnEventList[i], writer);
      writer.ldelim();
    }

    const mintEventList = message.mintEventList;
    for (let i: i32 = 0; i < mintEventList.length; ++i) {
      writer.uint32(18);
      writer.fork();
      MintEvent.encode(mintEventList[i], writer);
      writer.ldelim();
    }

    const stakeEventList = message.stakeEventList;
    for (let i: i32 = 0; i < stakeEventList.length; ++i) {
      writer.uint32(26);
      writer.fork();
      StakeEvent.encode(stakeEventList[i], writer);
      writer.ldelim();
    }

    const unstakeEventList = message.unstakeEventList;
    for (let i: i32 = 0; i < unstakeEventList.length; ++i) {
      writer.uint32(34);
      writer.fork();
      UnstakeEvent.encode(unstakeEventList[i], writer);
      writer.ldelim();
    }

    const wrapEventList = message.wrapEventList;
    for (let i: i32 = 0; i < wrapEventList.length; ++i) {
      writer.uint32(42);
      writer.fork();
      WrapEvent.encode(wrapEventList[i], writer);
      writer.ldelim();
    }

    const initAssetManagerList = message.initAssetManagerList;
    for (let i: i32 = 0; i < initAssetManagerList.length; ++i) {
      writer.uint32(50);
      writer.fork();
      InitAssetManager.encode(initAssetManagerList[i], writer);
      writer.ldelim();
    }

    const stakeList = message.stakeList;
    for (let i: i32 = 0; i < stakeList.length; ++i) {
      writer.uint32(58);
      writer.fork();
      Stake.encode(stakeList[i], writer);
      writer.ldelim();
    }

    const unstakeList = message.unstakeList;
    for (let i: i32 = 0; i < unstakeList.length; ++i) {
      writer.uint32(66);
      writer.fork();
      Unstake.encode(unstakeList[i], writer);
      writer.ldelim();
    }

    const wrapAssetList = message.wrapAssetList;
    for (let i: i32 = 0; i < wrapAssetList.length; ++i) {
      writer.uint32(74);
      writer.fork();
      WrapAsset.encode(wrapAssetList[i], writer);
      writer.ldelim();
    }

    const unwrapAssetList = message.unwrapAssetList;
    for (let i: i32 = 0; i < unwrapAssetList.length; ++i) {
      writer.uint32(82);
      writer.fork();
      UnwrapAsset.encode(unwrapAssetList[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Data {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Data();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.burnEventList.push(BurnEvent.decode(reader, reader.uint32()));
          break;

        case 2:
          message.mintEventList.push(MintEvent.decode(reader, reader.uint32()));
          break;

        case 3:
          message.stakeEventList.push(
            StakeEvent.decode(reader, reader.uint32())
          );
          break;

        case 4:
          message.unstakeEventList.push(
            UnstakeEvent.decode(reader, reader.uint32())
          );
          break;

        case 5:
          message.wrapEventList.push(WrapEvent.decode(reader, reader.uint32()));
          break;

        case 6:
          message.initAssetManagerList.push(
            InitAssetManager.decode(reader, reader.uint32())
          );
          break;

        case 7:
          message.stakeList.push(Stake.decode(reader, reader.uint32()));
          break;

        case 8:
          message.unstakeList.push(Unstake.decode(reader, reader.uint32()));
          break;

        case 9:
          message.wrapAssetList.push(WrapAsset.decode(reader, reader.uint32()));
          break;

        case 10:
          message.unwrapAssetList.push(
            UnwrapAsset.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  burnEventList: Array<BurnEvent>;
  mintEventList: Array<MintEvent>;
  stakeEventList: Array<StakeEvent>;
  unstakeEventList: Array<UnstakeEvent>;
  wrapEventList: Array<WrapEvent>;
  initAssetManagerList: Array<InitAssetManager>;
  stakeList: Array<Stake>;
  unstakeList: Array<Unstake>;
  wrapAssetList: Array<WrapAsset>;
  unwrapAssetList: Array<UnwrapAsset>;

  constructor(
    burnEventList: Array<BurnEvent> = [],
    mintEventList: Array<MintEvent> = [],
    stakeEventList: Array<StakeEvent> = [],
    unstakeEventList: Array<UnstakeEvent> = [],
    wrapEventList: Array<WrapEvent> = [],
    initAssetManagerList: Array<InitAssetManager> = [],
    stakeList: Array<Stake> = [],
    unstakeList: Array<Unstake> = [],
    wrapAssetList: Array<WrapAsset> = [],
    unwrapAssetList: Array<UnwrapAsset> = []
  ) {
    this.burnEventList = burnEventList;
    this.mintEventList = mintEventList;
    this.stakeEventList = stakeEventList;
    this.unstakeEventList = unstakeEventList;
    this.wrapEventList = wrapEventList;
    this.initAssetManagerList = initAssetManagerList;
    this.stakeList = stakeList;
    this.unstakeList = unstakeList;
    this.wrapAssetList = wrapAssetList;
    this.unwrapAssetList = unwrapAssetList;
  }
}
