// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InitAssetManager {
  static encode(message: InitAssetManager, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(16);
    writer.uint64(message.limit);

    writer.uint32(26);
    writer.string(message.contractUri);

    writer.uint32(32);
    writer.int64(message.startTime);

    writer.uint32(40);
    writer.int64(message.endTime);

    writer.uint32(48);
    writer.uint64(message.wrapFee);

    writer.uint32(56);
    writer.uint64(message.unwrapFee);

    writer.uint32(66);
    writer.string(message.acctOwner);

    writer.uint32(74);
    writer.string(message.acctAssetManager);
  }

  static decode(reader: Reader, length: i32): InitAssetManager {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitAssetManager();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.limit = reader.uint64();
          break;

        case 3:
          message.contractUri = reader.string();
          break;

        case 4:
          message.startTime = reader.int64();
          break;

        case 5:
          message.endTime = reader.int64();
          break;

        case 6:
          message.wrapFee = reader.uint64();
          break;

        case 7:
          message.unwrapFee = reader.uint64();
          break;

        case 8:
          message.acctOwner = reader.string();
          break;

        case 9:
          message.acctAssetManager = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  limit: u64;
  contractUri: string;
  startTime: i64;
  endTime: i64;
  wrapFee: u64;
  unwrapFee: u64;
  acctOwner: string;
  acctAssetManager: string;

  constructor(
    trxHash: string = "",
    limit: u64 = 0,
    contractUri: string = "",
    startTime: i64 = 0,
    endTime: i64 = 0,
    wrapFee: u64 = 0,
    unwrapFee: u64 = 0,
    acctOwner: string = "",
    acctAssetManager: string = ""
  ) {
    this.trxHash = trxHash;
    this.limit = limit;
    this.contractUri = contractUri;
    this.startTime = startTime;
    this.endTime = endTime;
    this.wrapFee = wrapFee;
    this.unwrapFee = unwrapFee;
    this.acctOwner = acctOwner;
    this.acctAssetManager = acctAssetManager;
  }
}
