// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class MintEvent {
  static encode(message: MintEvent, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(18);
    writer.string(message.assetAccount);

    writer.uint32(26);
    writer.string(message.mintAccount);

    writer.uint32(34);
    writer.string(message.tokenAccount);
  }

  static decode(reader: Reader, length: i32): MintEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MintEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.assetAccount = reader.string();
          break;

        case 3:
          message.mintAccount = reader.string();
          break;

        case 4:
          message.tokenAccount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  assetAccount: string;
  mintAccount: string;
  tokenAccount: string;

  constructor(
    trxHash: string = "",
    assetAccount: string = "",
    mintAccount: string = "",
    tokenAccount: string = ""
  ) {
    this.trxHash = trxHash;
    this.assetAccount = assetAccount;
    this.mintAccount = mintAccount;
    this.tokenAccount = tokenAccount;
  }
}
