// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class StakeEvent {
  static encode(message: StakeEvent, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(18);
    writer.string(message.assetAccount);

    writer.uint32(26);
    writer.string(message.stakeAccount);

    writer.uint32(34);
    writer.string(message.mintAccount);

    writer.uint32(42);
    writer.string(message.ownerAccount);

    writer.uint32(50);
    writer.string(message.authorityAccount);

    writer.uint32(58);
    writer.string(message.ownerTokenAccount);

    writer.uint32(66);
    writer.string(message.stakerTokenAccount);
  }

  static decode(reader: Reader, length: i32): StakeEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StakeEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.assetAccount = reader.string();
          break;

        case 3:
          message.stakeAccount = reader.string();
          break;

        case 4:
          message.mintAccount = reader.string();
          break;

        case 5:
          message.ownerAccount = reader.string();
          break;

        case 6:
          message.authorityAccount = reader.string();
          break;

        case 7:
          message.ownerTokenAccount = reader.string();
          break;

        case 8:
          message.stakerTokenAccount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  assetAccount: string;
  stakeAccount: string;
  mintAccount: string;
  ownerAccount: string;
  authorityAccount: string;
  ownerTokenAccount: string;
  stakerTokenAccount: string;

  constructor(
    trxHash: string = "",
    assetAccount: string = "",
    stakeAccount: string = "",
    mintAccount: string = "",
    ownerAccount: string = "",
    authorityAccount: string = "",
    ownerTokenAccount: string = "",
    stakerTokenAccount: string = ""
  ) {
    this.trxHash = trxHash;
    this.assetAccount = assetAccount;
    this.stakeAccount = stakeAccount;
    this.mintAccount = mintAccount;
    this.ownerAccount = ownerAccount;
    this.authorityAccount = authorityAccount;
    this.ownerTokenAccount = ownerTokenAccount;
    this.stakerTokenAccount = stakerTokenAccount;
  }
}
