// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class Stake {
  static encode(message: Stake, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(16);
    writer.uint64(message.stakeNo);

    writer.uint32(26);
    writer.string(message.acctOwner);

    writer.uint32(34);
    writer.string(message.acctAuthority);

    writer.uint32(42);
    writer.string(message.acctAssetManager);

    writer.uint32(50);
    writer.string(message.acctAsset);

    writer.uint32(58);
    writer.string(message.acctStake);

    writer.uint32(66);
    writer.string(message.acctMintAccount);

    writer.uint32(74);
    writer.string(message.acctOwnerTokenAccount);

    writer.uint32(82);
    writer.string(message.acctAuthorityTokenAccount);
  }

  static decode(reader: Reader, length: i32): Stake {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Stake();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.stakeNo = reader.uint64();
          break;

        case 3:
          message.acctOwner = reader.string();
          break;

        case 4:
          message.acctAuthority = reader.string();
          break;

        case 5:
          message.acctAssetManager = reader.string();
          break;

        case 6:
          message.acctAsset = reader.string();
          break;

        case 7:
          message.acctStake = reader.string();
          break;

        case 8:
          message.acctMintAccount = reader.string();
          break;

        case 9:
          message.acctOwnerTokenAccount = reader.string();
          break;

        case 10:
          message.acctAuthorityTokenAccount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  stakeNo: u64;
  acctOwner: string;
  acctAuthority: string;
  acctAssetManager: string;
  acctAsset: string;
  acctStake: string;
  acctMintAccount: string;
  acctOwnerTokenAccount: string;
  acctAuthorityTokenAccount: string;

  constructor(
    trxHash: string = "",
    stakeNo: u64 = 0,
    acctOwner: string = "",
    acctAuthority: string = "",
    acctAssetManager: string = "",
    acctAsset: string = "",
    acctStake: string = "",
    acctMintAccount: string = "",
    acctOwnerTokenAccount: string = "",
    acctAuthorityTokenAccount: string = ""
  ) {
    this.trxHash = trxHash;
    this.stakeNo = stakeNo;
    this.acctOwner = acctOwner;
    this.acctAuthority = acctAuthority;
    this.acctAssetManager = acctAssetManager;
    this.acctAsset = acctAsset;
    this.acctStake = acctStake;
    this.acctMintAccount = acctMintAccount;
    this.acctOwnerTokenAccount = acctOwnerTokenAccount;
    this.acctAuthorityTokenAccount = acctAuthorityTokenAccount;
  }
}
