// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class UnwrapAsset {
  static encode(message: UnwrapAsset, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(16);
    writer.uint64(message.supplyNo);

    writer.uint32(26);
    writer.string(message.acctOwner);

    writer.uint32(34);
    writer.string(message.acctAuthority);

    writer.uint32(42);
    writer.string(message.acctAssetManager);

    writer.uint32(50);
    writer.string(message.acctAsset);
  }

  static decode(reader: Reader, length: i32): UnwrapAsset {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new UnwrapAsset();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.supplyNo = reader.uint64();
          break;

        case 3:
          message.acctOwner = reader.string();
          break;

        case 4:
          message.acctAuthority = reader.string();
          break;

        case 5:
          message.acctAssetManager = reader.string();
          break;

        case 6:
          message.acctAsset = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  supplyNo: u64;
  acctOwner: string;
  acctAuthority: string;
  acctAssetManager: string;
  acctAsset: string;

  constructor(
    trxHash: string = "",
    supplyNo: u64 = 0,
    acctOwner: string = "",
    acctAuthority: string = "",
    acctAssetManager: string = "",
    acctAsset: string = ""
  ) {
    this.trxHash = trxHash;
    this.supplyNo = supplyNo;
    this.acctOwner = acctOwner;
    this.acctAuthority = acctAuthority;
    this.acctAssetManager = acctAssetManager;
    this.acctAsset = acctAsset;
  }
}
