// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { AssetInfo } from "./AssetInfo";

export class WrapEvent {
  static encode(message: WrapEvent, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    const assetInfo = message.assetInfo;
    if (assetInfo !== null) {
      writer.uint32(18);
      writer.fork();
      AssetInfo.encode(assetInfo, writer);
      writer.ldelim();
    }

    writer.uint32(26);
    writer.string(message.assetAccount);

    writer.uint32(34);
    writer.string(message.owner);
  }

  static decode(reader: Reader, length: i32): WrapEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new WrapEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.assetInfo = AssetInfo.decode(reader, reader.uint32());
          break;

        case 3:
          message.assetAccount = reader.string();
          break;

        case 4:
          message.owner = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  assetInfo: AssetInfo | null;
  assetAccount: string;
  owner: string;

  constructor(
    trxHash: string = "",
    assetInfo: AssetInfo | null = null,
    assetAccount: string = "",
    owner: string = ""
  ) {
    this.trxHash = trxHash;
    this.assetInfo = assetInfo;
    this.assetAccount = assetAccount;
    this.owner = owner;
  }
}
