// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Asset } from "./Asset";

export class WrapAsset {
  static encode(message: WrapAsset, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    const assets = message.assets;
    for (let i: i32 = 0; i < assets.length; ++i) {
      writer.uint32(18);
      writer.fork();
      Asset.encode(assets[i], writer);
      writer.ldelim();
    }

    writer.uint32(26);
    writer.string(message.acctOwner);

    writer.uint32(34);
    writer.string(message.acctAuthority);

    writer.uint32(42);
    writer.string(message.acctAssetManager);

    writer.uint32(50);
    writer.string(message.acctAsset);
  }

  static decode(reader: Reader, length: i32): WrapAsset {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new WrapAsset();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.assets.push(Asset.decode(reader, reader.uint32()));
          break;

        case 3:
          message.acctOwner = reader.string();
          break;

        case 4:
          message.acctAuthority = reader.string();
          break;

        case 5:
          message.acctAssetManager = reader.string();
          break;

        case 6:
          message.acctAsset = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  assets: Array<Asset>;
  acctOwner: string;
  acctAuthority: string;
  acctAssetManager: string;
  acctAsset: string;

  constructor(
    trxHash: string = "",
    assets: Array<Asset> = [],
    acctOwner: string = "",
    acctAuthority: string = "",
    acctAssetManager: string = "",
    acctAsset: string = ""
  ) {
    this.trxHash = trxHash;
    this.assets = assets;
    this.acctOwner = acctOwner;
    this.acctAuthority = acctAuthority;
    this.acctAssetManager = acctAssetManager;
    this.acctAsset = acctAsset;
  }
}
